### ISSUE TITLE
Calls through a proxy

### ISSUE THREAD

**Issue by ctranquilli** [PAXSTORE/paxstore-openapi-java-sdk#12]
Hi, 
Is it possible to set up a proxy for calls made with the API?

Thanks

**Comment by reestolonio** [comment]
Any update on this?

**Comment by paxstore-support** [comment]
currently proxy is not supported

**Comment by paxstore-support** [comment]
please set system properties
https://docs.oracle.com/javase/8/docs/technotes/guides/net/proxies.html
