### ISSUE TITLE
Missing how to add to gradle / maven to README

### ISSUE THREAD

**Issue by mathmul** [PAXSTORE/paxstore-openapi-java-sdk#23]
In my Quarkus Kotlin project I tried adding
```
    implementation("com.pax.market:paxstore-openapi-java-sdk:7.4.0")
```
but it only started working once I added the deprecated `jcenter()` to `repositories {}`.

**Comment by paxstore-support** [comment]
Please use the latest version like 9.3.0. We do not publish to jcenter now.

**Comment by mathmul** [comment]
Yes, sorry. I did later on... Closing this issue. The latest version still has issues though: https://github.com/PAXSTORE/paxstore-openapi-java-sdk/issues/24
